### ISSUE TITLE
(401: Unauthorized) Token telah expire mohon login kembali

### ISSUE THREAD

**Issue by nolbyte** [mrizkir/stiemu#10]
Selamat siang
Pada saat mencoba login, saya mendapat error seperti itu.
Mohon maaf karena saya baru mencoba vue dan laravel
Terima kasih

**Comment by mrizkir** [comment]
Tidak apa2. 

Coba clone lagi repo yang ini; untuk mendapatkan update terbaru.

Berkaitan dengan error yang itu pastikan file .env.local sudah ada didalam folder frontend. Berikut contoh isi file .env.loca didalam folder frontend:

```
VUE_APP_NAME="PortalEkampus v3"
VUE_APP_API_HOST='http://localhost:8000'
VUE_APP_APIUrlV3='http://localhost:8000/v3'
```
